=== sangnguyensoftware/openunderwriter/build/schema/Configuration-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration" />

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="timeout" type="xs:integer" minOccurs="1" maxOccurs="1" />
                <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders" />
                <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types" />
                <xs:element name="XMLMapping" minOccurs="0" maxOccurs="1" type="XMLMapping" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                    <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="service" type="Service" />
                <xs:element name="command" type="Command" />
                <xs:element name="type" type="Type" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- In Java the Service class extends Type, not Group as here. However, XSD doesn't allow an attribute to be overridden with another of the same name but different type. The 'key' attribute would 
        fall foul of this limitation, so Group is extended instead. -->
    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="required" type="availableAccessors" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="optional" type="xs:string" />
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XMLMapping">
        <xs:sequence>
            <xs:element name="definition" minOccurs="1" maxOccurs="1" type="XMLMappingDefinition" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XMLMappingDefinition" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" processContents="skip" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder" />
            <xs:enumeration value="CastorXMLBuilder" />
            <xs:enumeration value="BeanShellBuilder" />
            <xs:enumeration value="ClassBuilder" />
            <xs:enumeration value="CachingClassBuilder" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor" />
            <xs:enumeration value="com.ail.core.command.ClassAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor" />
            <xs:enumeration value="com.ail.core.command.EJBAccessor" />
            <xs:enumeration value="com.ail.core.command.JaninoAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaScriptAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaAccessor" />
            <xs:enumeration value="com.ail.core.command.JMSAccessor" />
            <xs:enumeration value="com.ail.core.command.QuickRulesAccessor" />
            <xs:enumeration value="com.ail.core.command.VelocityAccessor" />
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor" />
            <xs:enumeration value="com.ail.core.command.XSLTAccessor" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== sangnguyensoftware/openunderwriter/demo-product-loader-hook.war/src/Product/AIL/Demo/TravelPlus/Registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
  <name>TravePlus product configuration</name>
  <timeout>-1</timeout>
  <who>Applied Industrial Logic</who>
  <version>1.0</version> 

  <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
  <parentNamespace>AIL.Base.Registry</parentNamespace>

  <types>

	<service name="AssessSectionRiskRule/Section" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor" >
      <!--parameter name="LoggingIndicatorAsString">FULL</parameter-->
      <parameter name="Url">~/Rules/SectionRating.xls</parameter>
    </service>

	<service name="CalculatePolicyTaxRule" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor"> 
	  <parameter name="Url">~/Rules/CalculatePolicyTaxRule.xls</parameter>
	</service>

    <service name="EnforceCoveragesService" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor" >
      <parameter name="Url">~/Rules/EnforceCoverages.xls</parameter>
    </service>
        
	<service name="AnswerSection/html" builder="CachingClassBuilder" key="com.ail.core.command.VelocityAccessor">
		<parameter name="Url">~/Templates/AnswerSection.vel</parameter>
	</service>
	
	<service name="SelectSectionService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
		<parameter name="Url">~/Services/SelectSectionService.java</parameter> 
	</service>

	<service name="SetPolicyStatusService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
		<parameter name="Url">~/Services/SetPolicyStatusService.java</parameter>
	</service>

	<service name="AddPayPalMoneyProvisionToPolicyService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
		<parameter name="Url">~/Services/AddPayPalMoneyProvisionToPolicyService.java</parameter>
	</service>

	<service name="ResetPayPalMoneyProvisionInPolicyService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
		<parameter name="Url">~/Services/ResetPayPalMoneyProvisionInPolicyService.java</parameter>
	</service>

    <service name="TravellersValidationService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor" >
      	<parameter name="Url">~/Services/TravellersValidationService.java</parameter>
    </service>
    
    <service name="PolicyDetail/html" builder="CachingClassBuilder" key="com.ail.core.command.VelocityAccessor">
		<parameter name="Url">~/Templates/PolicyDetail.vel</parameter>
	</service>

    <command name="AssessPolicyRisk" key="com.ail.insurance.quotation.AssessPolicyRiskCommandImpl">
      <!-- There are no risk assessment rules at the policy level for this product, all risk assessment -->
      <!-- is done at the section level. The NullService has the effect of saying 'do nothing'.           -->
      <parameter name="Service">com.ail.core.NullService</parameter>
    </command>
        
    <command name="AssessSectionRisk/Section" builder="CachingClassBuilder" key="com.ail.insurance.quotation.AssessSectionRiskCommandImpl" >
      <parameter name="Service">AssessSectionRiskRule/Section</parameter>
    </command>

    <command name="EnforceCoverages" key="com.ail.pageflow.ExecutePageActionCommandImpl">
      <parameter name="Service">EnforceCoveragesService</parameter>
    </command>

	<command name="SelectSection" key="com.ail.pageflow.ExecutePageActionCommandImpl">
		<parameter name="Service">SelectSectionService</parameter>
	</command>

	<command name="SetPolicyStatus" key="com.ail.pageflow.ExecutePageActionCommandImpl">
		<parameter name="Service">SetPolicyStatusService</parameter>
	</command>

	<command name="AddPayPalMoneyProvisionToPolicy" key="com.ail.pageflow.ExecutePageActionCommandImpl">
		<parameter name="Service">AddPayPalMoneyProvisionToPolicyService</parameter>
	</command>
 
	<command name="ResetPayPalMoneyProvisionInPolicy" key="com.ail.pageflow.ExecutePageActionCommandImpl">
		<parameter name="Service">ResetPayPalMoneyProvisionInPolicyService</parameter>
	</command>

    <command name="TravellersValidation" key="com.ail.pageflow.ExecutePageActionCommandImpl">
      <parameter name="Service">TravellersValidationService</parameter>
    </command>
 
    <type name="Policy" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Policy">
      <parameter name="extends">super.Policy</parameter>
      <parameter name="Url">~/Model/Policy.xml</parameter>
    </type>
	
    <type name="TravellerAsset" builder="CastorXMLBuilder" singleInstance="false" key="com.ail.insurance.policy.Asset">
      <parameter name="Url">~/Model/TravellerAsset.xml</parameter>
    </type>

	<type name='Broker' builder='CastorXMLBuilder' key='com.ail.insurance.policy.Broker'>
      <parameter name="Url">~/Model/Broker.xml</parameter>
	</type>
	
    <type name="QuotationPageFlow" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.PageFlow">
      <parameter name="extends">super.QuotationPageFlow</parameter>
      <parameter name="Url">~/PageFlows/QuotationPageFlow.xml</parameter>
    </type>

	<type name="QuotationDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
		<parameter name="extends">super.QuotationDocument</parameter>
		<parameter name="Url">~/Documents/QuotationDocument.xml</parameter>
	</type>

	<type name="CertificateDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
		<parameter name="extends">super.CertificateDocument</parameter>
		<parameter name="Url">~/Documents/CertificateDocument.xml</parameter>
	</type>
	
    <type name="Translations" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.language.Translations">
      <parameter name="Extends">super.Translations</parameter>
      <parameter name="Url">~/Localisation/Translations.xml</parameter>
    </type>
	
  </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/persistence/hibernate/TestCoreHibernatePersistenceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
  <name>Default Service Invocation Configuration</name>
  <timeout>600000</timeout>
  <who>factory</who>
  <version>$Revision: 1.6 $</version>

  <types>
    <!--============================================ -->
    <!-- Define the (local) component's services -->
    <!--============================================ -->
    <service name="CreateService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateCreateService</parameter>
    </service>
    <service name="UpdateService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateUpdateService</parameter>
    </service>
    <service name="LoadService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateLoadService</parameter>
    </service>
    <service name="QueryService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateQueryService</parameter>
    </service>
    <service name="DeleteService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateDeleteService</parameter>
    </service>
    <service name="OpenSessionService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateOpenSessionService</parameter>
    </service>
    <service name="CloseSessionService" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateCloseSessionService</parameter>
    </service>

    <!--============================================ -->
    <!-- Define the (remote) component's services -->
    <!--============================================ -->
    <service name='PersistenceService' builder='ClassBuilder' key='com.ail.core.command.EJBAccessor'>
      <parameter name='JndiName'>PersistenceServer</parameter>
    </service>

    <!--======================================================================= -->
    <!-- Bind the default core services (above) to Commands used by Core.class -->
    <!--======================================================================= -->
    <command name="Create" key="com.ail.core.persistence.CreateCommandImpl">
      <parameter name="Service">CreateService</parameter>
    </command>

    <command name="Update" key="com.ail.core.persistence.UpdateCommandImpl">
      <parameter name="Service">UpdateService</parameter>
    </command>

    <command name="Load" key="com.ail.core.persistence.LoadCommandImpl">
      <parameter name="Service">LoadService</parameter>
    </command>

    <command name="Query" key="com.ail.core.persistence.QueryCommandImpl">
      <parameter name="Service">QueryService</parameter>
    </command>

    <command name="Delete" key="com.ail.core.persistence.DeleteCommandImpl">
      <parameter name="Service">DeleteService</parameter>
    </command>

    <command name="OpenSession" key="com.ail.core.persistence.OpenSessionCommandImpl">
      <parameter name="Service">OpenSessionService</parameter>
    </command>

    <command name="CloseSession" key="com.ail.core.persistence.CloseSessionCommandImpl">
      <parameter name="Service">CloseSessionService</parameter>
    </command>

    <!--=================================================================================================== -->
    <!-- Bind remote persistence services to the PersistenceServce (in com/ail/core/CoreDefaultConfig.xml) -->
    <!--=================================================================================================== -->
    <command name="TestCreateCommandRemote" key="com.ail.core.persistence.CreateCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestUpdateCommandRemote" key="com.ail.core.persistence.UpdateCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestLoadCommandRemote" key="com.ail.core.persistence.LoadCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestQueryCommandRemote" key="com.ail.core.persistence.QueryCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestOpenSessionCommandRemote" key="com.ail.core.persistence.OpenSessionCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestCloseSessionCommandRemote" key="com.ail.core.persistence.CloseSessionCommandImpl">
      <parameter name="Service">PersistenceService</parameter>
    </command>

  </types>
</configuration>
