=== sangnguyensoftware/openunderwriter/build/schema/Configuration-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration" />

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="timeout" type="xs:integer" minOccurs="1" maxOccurs="1" />
                <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders" />
                <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types" />
                <xs:element name="XMLMapping" minOccurs="0" maxOccurs="1" type="XMLMapping" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                    <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="service" type="Service" />
                <xs:element name="command" type="Command" />
                <xs:element name="type" type="Type" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- In Java the Service class extends Type, not Group as here. However, XSD doesn't allow an attribute to be overridden with another of the same name but different type. The 'key' attribute would 
        fall foul of this limitation, so Group is extended instead. -->
    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="required" type="availableAccessors" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="optional" type="xs:string" />
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XMLMapping">
        <xs:sequence>
            <xs:element name="definition" minOccurs="1" maxOccurs="1" type="XMLMappingDefinition" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XMLMappingDefinition" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" processContents="skip" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder" />
            <xs:enumeration value="CastorXMLBuilder" />
            <xs:enumeration value="BeanShellBuilder" />
            <xs:enumeration value="ClassBuilder" />
            <xs:enumeration value="CachingClassBuilder" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor" />
            <xs:enumeration value="com.ail.core.command.ClassAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor" />
            <xs:enumeration value="com.ail.core.command.EJBAccessor" />
            <xs:enumeration value="com.ail.core.command.JaninoAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaScriptAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaAccessor" />
            <xs:enumeration value="com.ail.core.command.JMSAccessor" />
            <xs:enumeration value="com.ail.core.command.QuickRulesAccessor" />
            <xs:enumeration value="com.ail.core.command.VelocityAccessor" />
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor" />
            <xs:enumeration value="com.ail.core.command.XSLTAccessor" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== sangnguyensoftware/openunderwriter/modules/com/ail/core.jar/com/ail/core/command/OnMessageDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>CommandServerBean configuration</name>
  <timeout>-1</timeout>
  <who>factory</who>
  <version>$Revision$</version>

  <types>
  
  	<service name="SendEmailService" key="com.ail.core.command.SpringAccessor">
      <parameter name="ServiceClass">com.ail.core.email.SendEmailService</parameter>
    </service>
    
    <command name="SendEmailArgumentImpl" key="com.ail.core.email.SendEmailCommandImpl">
      <parameter name="Service">SendEmailService</parameter>
    </command>
    
    <command name="LoggingArgumentImpl" key="com.ail.core.logging.LoggingCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>

    <command name="ClearProductCacheArgumentImpl" key="com.ail.core.product.ClearProductCacheCommandImpl">
      <parameter name="Service">com.ail.core.product.ClearProductCacheService</parameter>
    </command>
    
    <command name="ResetProductArgumentImpl" key="com.ail.core.product.ResetProductCommandImpl">
      <parameter name="Service">com.ail.core.product.ResetProductService</parameter>
    </command>

    <command name="RegisterProductArgumentImpl" key="com.ail.core.product.RegisterProductCommandImpl">
      <parameter name="Service">com.ail.core.product.liferay.LiferayRegisterProductService</parameter>
    </command>

    <command name="RemoveProductArgumentImpl" key="com.ail.core.product.RemoveProductCommandImpl">
      <parameter name="Service">com.ail.core.product.RemoveProductService</parameter>
    </command>

    <!--======================================================================= -->
    <!-- Bind the command server's commands directly to an implementation; -->
    <!-- hibernate by default. This ensures that the command server won't -->
    <!-- invoke the core's bindings - which may point at some wrapper (like -->
    <!-- the command server itself!). -->
    <!--======================================================================= -->
    <command name="Update" key="com.ail.core.persistence.UpdateCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateUpdateService</parameter>
    </command>

    <command name="Query" key="com.ail.core.persistence.QueryCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateQueryService</parameter>
    </command>

    <command name="Load" key="com.ail.core.persistence.LoadCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateLoadService</parameter>
    </command>

    <command name="Create" key="com.ail.core.persistence.CreateCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateCreateService</parameter>
    </command>

    <command name="Delete" key="com.ail.core.persistence.DeleteCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateDeleteService</parameter>
    </command>

    <command name="OpenPersistenceSession" key="com.ail.core.persistence.OpenSessionCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateOpenSessionService</parameter>
    </command>

    <command name="ClosePersistenceSession" key="com.ail.core.persistence.CloseSessionCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateCloseSessionService</parameter>
    </command>
  </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/insurance/TestAcceptanceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Default Test Acceptance Configuration</name>
    <timeout>600000</timeout>
    <who>factory</who>
    <version>$Revision: 1.3 $</version>

    <group name="KeyGenerators">
        <group name="QuoteNumber">
            <parameter name="ID">Base.QuoteNumber</parameter>
            <parameter name="Range">1000-*</parameter>
        </group>
        <group name="PolicyNumber">
            <parameter name="ID">Base.PolicyNumber</parameter>
            <parameter name="Range">1000-*</parameter>
        </group>
        <group name="InvoiceNumber">
            <parameter name="ID">Base.InvoiceNumber</parameter>
            <parameter name="Range">1000-*</parameter>
        </group>
    </group>

    <types>
        <!--==================================== -->
        <!-- Define the component's services -->
        <!--==================================== -->
        <service name="AcceptanceComponent" key="com.ail.core.command.EJBAccessor">
            <parameter name="JndiName">Acceptance</parameter>
        </service>

        <!--======================================================================= -->
        <!-- Bind the default core services (above) to Commands used by Core.class -->
        <!--======================================================================= -->
        <command name="PutOnRiskService" key="com.ail.insurance.acceptance.PutOnRiskCommandImpl">
            <parameter name="Service">AcceptanceComponent</parameter>
        </command>
        <command name="ProduceDocumentationService" key="com.ail.insurance.acceptance.ProduceDocumentationCommandImpl">
            <parameter name="Service">AcceptanceComponent</parameter>
        </command>
        <command name="CollectPremiumService" key="com.ail.insurance.acceptance.CollectPremiumCommandImpl">
            <parameter name="Service">AcceptanceComponent</parameter>
        </command>
        <command name="AddPolicyNumber" key="com.ail.insurance.quotation.addpolicynumber.AddPolicyNumberCommandImpl">
            <parameter name="Service">AcceptanceComponent</parameter>
        </command>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/product/ProductCatalogDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration use by ListProducts service.
 The configuration defines the products that are know to the system.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>ProductCatalog configuration</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision: 1.2 $</version>
    <manager>com.ail.core.product.listproducts.ListProductsService</manager>
    
    <group name="products">
        <parameter name="com.ail.core.product.TestProduct01"/>
        <parameter name="com.ail.core.product.TestProduct02"/>
        <parameter name="com.ail.core.product.TestProduct03"/>
        <parameter name="com.ail.core.product.TestProduct04"/>
        <parameter name="com.ail.core.product.TestProduct05"/>
        <parameter name="com.ail.core.product.TestProduct06"/>
        <parameter name="com.ail.core.product.TestProduct07"/>
        <parameter name="com.ail.core.product.TestProduct08"/>
        <parameter name="com.ail.core.product.TestProduct09"/>
        <parameter name="com.ail.core.product.TestProduct10"/>
        <parameter name="com.ail.core.product.TestProduct11"/>
        <parameter name="com.ail.core.product.TestProduct12"/>
    </group>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/product/TestProduct05/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product for use in the core system. This product configuration is
 not required in live deployments and is only used for testing purposes.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>Configuration for Test Product 5</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>1.0</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.TestProduct04.Registry</parentNamespace>
    
    <types>
        <service name="PolicyRule" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 'flag' - just to show that this rule has been run */
                line=new FixedSum();
                line.setId("flag");
                line.setAmount(new CurrencyAmount(0.0, Currency.GBP));
                as.addLine(line);
            ]]></parameter>
        </service>

        <service name="SectionRule" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.util.Rate;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 'sum insured' for 500.00 GBP*/
                line=new FixedSum();
                line.setId("sum insured");
                line.setAmount(new CurrencyAmount(500.00, Currency.GBP));
                as.addLine(line);
                
                /* add a loading of 5% for no reason! */
                line=new RateBehaviour();
                line.setId("loading1");
                line.setDependsOn("sum insured");
                line.setContributesTo("policy.total premium");
                line.setRate(new Rate("50%"));;
                line.setType(BehaviourType.LOAD);
                line.setReason("No reason what so ever!");
                as.addLine(line);
            ]]></parameter>
        </service>
        
        <!-- Tax calc rules (command & service) for this product -->
        <command name="CalculatePolicyTax" key="com.ail.insurance.quotation.CalculatePolicyTaxCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>

        <!-- Risk assessment rules (command & service) for all products unless they override -->
        <command name="AssessPolicyRisk" key="com.ail.insurance.quotation.AssessPolicyRiskCommandImpl">
            <parameter name="Service">PolicyRule</parameter>
        </command>

        <command name="AssessSectionRisk/TestSectionTwoID" key="com.ail.insurance.quotation.AssessSectionRiskCommandImpl">
            <parameter name="Service">SectionRule</parameter>
        </command>

        <type name="TestProduct05" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Script"><![CDATA[
                import com.ail.insurance.policy.*;
                
                policy=new Policy();
                policy.setProductTypeId("com.ail.core.product.TestProduct05");
                section=new Section();
                section.setId("sec1");
                section.setSectionTypeId("TestSectionTwoID");
                policy.addSection(section);
                policy.setStatus(PolicyStatus.APPLICATION);
                type=policy;
            ]]></parameter>
        </type>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/demo-product-loader-hook.war/src/Product/AIL/Demo/EquinePlus/Registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>Equine Plus product configuration</name>
    <timeout>-1</timeout>
    <parentNamespace>AIL.Base.Registry</parentNamespace>
    <who>Applied Industrial Logic</who>
    <version>1.1</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>

    <group name="SecuredServices">
        <parameter name="CreatePolicy">PermitAll</parameter>
    </group>
    
    <group name="jBPMProperties">
        <parameter name="jbpm.console.protocol">http</parameter>
        <parameter name="jbpm.console.hostname">localhost</parameter>
        <parameter name="jbpm.console.port">8080</parameter>
        <parameter name="jbpm.console.username">katie@openunderwriter.org</parameter>
        <parameter name="jbpm.console.password">katie</parameter>
        <parameter name="jbpm.deployment.id">ail:sample-workflows:1.0</parameter>
        <parameter name="jbpm.policy.pageflow.default">PolicyDetailPageFlow</parameter>
        <parameter name="jbpm.policy.page.default">Main</parameter>
        <parameter name="jbpm.party.pageflow.default">ClientDetailsPageFlow</parameter>
        <parameter name="jbpm.party.page.default">Main</parameter>
    </group>
    
    <!-- Group of parameters to specify comma-separated lists of source folders under the product folder -->
    <group name="SourceFolders">
    	<parameter name="Java">JavaServices,Services,Rules</parameter>
    </group>

    <types>
        <service name="AssessPolicyRiskRule" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor" >
            <!-- parameter name="LoggingIndicatorAsString">FULL</parameter-->
            <parameter name="Url">~/Rules/PolicyRating.xls</parameter>
        </service>

        <service name="CalculatePolicyCommissionRule" builder="CachingClassBuilder" key="com.ail.core.command.JavaAccessor" />

        <service name="CalculatePolicyMgmtChgRule" builder="CachingClassBuilder" key="com.ail.core.command.JavaAccessor" />

        <service name="StyleDocumentService" key="com.ail.core.command.XSLTAccessor">
            <parameter name="Url">http://localhost:8080/openquote-theme/documents/style.xslt</parameter>
        </service>

        <command name="AssessSectionRisk/EquinePlusSection" builder="CachingClassBuilder" key="com.ail.insurance.quotation.AssessSectionRiskCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>
        
        <command name="AssessPaymentOptions" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">com.ail.demo.equineplus.AssessPaymentOptionsService</parameter>
        </command>
        
        <type name="Policy" builder="BeanShellBuilder">
            <parameter name="extends">super.Policy</parameter>
            <parameter name="Url">~/JavaServices/Policy.bs</parameter>
        </type>
        
        <!-- Equine section  -->
        <type name="EquinePlusSection" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Section">
            <parameter name="Url">~/Model/EquinePlusSection.xml</parameter>
        </type>
        
        <type name="SaddleryAndTackExcess" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Excess">
            <parameter name="Url">~/Model/SaddleryAndTackExcess.xml</parameter>
        </type>
        
        <type name="HorseAsset" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Asset">
            <parameter name="Url">~/Model/HorseAsset.xml</parameter>
        </type>
        
        <type name="CoverageAsset" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Asset">
            <parameter name="Url">~/Model/CoverageAsset.xml</parameter>
        </type>
        
        <type name="HorseAge" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.util.Choice"> 
            <parameter name="Url">~/Lists/HorseAge.xml</parameter>
        </type>
        
        <type name="HorseColour" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.util.Choice">
            <parameter name="Url">~/Lists/HorseColour.xml</parameter>
        </type>
        
        <type name="HorseHeightHands" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.util.Choice">
            <parameter name="Url">~/Lists/HorseHeightHands.xml</parameter>
        </type>
        
        <type name="QuotationPageFlow" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.PageFlow">
            <parameter name="Url">~/PageFlows/QuotationPageFlow.xml</parameter>
        </type>

        <type name="QuotationDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
			<parameter name="extends">super.QuotationDocument</parameter>
            <parameter name="Url">~/Documents/QuotationDocument.xml</parameter>
        </type>
        
        <type name="DataDictionary" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.data.DataDictionary">
			<parameter name="extends">super.DataDictionary</parameter>
            <parameter name="Url">~/DataDictionary.xml</parameter>
        </type>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/product/TestProduct11/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product which will always has two referrals.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>Configuration for Test Product 11</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>1.0</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.TestProduct04.Registry</parentNamespace>
    
    <types>
        <service name="PolicyRule" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add two lines - just to show that this rule has been run */
                as.addFixedSum("dummyid1", "Loading", null, "total premium", new CurrencyAmount(0.0, Currency.GBP));
                as.addReferral("dummyid3", "No reason", null);
                as.addReferral("dummyid4", "No reason", null);
            ]]></parameter>
        </service>

        <type name="TestProduct11" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Extends">TestProduct04</parameter>
            <parameter name="Script"><![CDATA[
                type=new com.ail.insurance.policy.Policy();
                type.setProductTypeId("com.ail.core.product.TestProduct11");
            ]]></parameter>
        </type>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/financial/ledger/service/TestCalculateAccountBalanceServiceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
	xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Default Test Acceptance Configuration</name>
	<timeout>600000</timeout>
	<who>factory</who>
	<version>$Revision: 1.3 $</version>

	<types>
		<service name="CalculateAccountBalance" key="com.ail.core.command.ClassAccessor">
			<parameter name="ServiceClass">com.ail.financial.service.CalculateAccountBalanceService</parameter>
		</service>

		<command name="com.ail.financial.service.CalculateAccountBalanceService.CalculateAccountBalanceCommand" key="com.ail.financial.service.CalculateAccountBalanceCommandImpl">
			<parameter name="Service">CalculateAccountBalance</parameter>
		</command>
	</types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/product/TestProduct12/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product which will always has two referrals.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>Configuration for Test Product 12</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>1.0</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.TestProduct04.Registry</parentNamespace>
    
    <types>
        <service name="PolicyRule" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.util.Rate;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                as.addLine(new FixedSum("base premium", "lookup", null, null, new CurrencyAmount("100.00", Currency.GBP)));
                as.addLine(new RateBehaviour("rateA", null, null, "net premium", "base premium", BehaviourType.LOAD, new Rate("10%")));
                as.addLine(new RateBehaviour("rateB", null, null, "net premium", "base premium", BehaviourType.LOAD, new Rate("10%")));
            ]]></parameter>
        </service>

        <type name="TestProduct12" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Extends">TestProduct04</parameter>
            <parameter name="Script"><![CDATA[
                type=new com.ail.insurance.policy.Policy();
                type.setProductTypeId("com.ail.core.product.TestProduct12");
            ]]></parameter>
        </type>
    </types>
</configuration>
