=== sangnguyensoftware/openunderwriter/build/schema/Configuration-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration" />

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="timeout" type="xs:integer" minOccurs="1" maxOccurs="1" />
                <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders" />
                <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types" />
                <xs:element name="XMLMapping" minOccurs="0" maxOccurs="1" type="XMLMapping" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter" />
                    <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="service" type="Service" />
                <xs:element name="command" type="Command" />
                <xs:element name="type" type="Type" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- In Java the Service class extends Type, not Group as here. However, XSD doesn't allow an attribute to be overridden with another of the same name but different type. The 'key' attribute would 
        fall foul of this limitation, so Group is extended instead. -->
    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="required" type="availableAccessors" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="optional" type="availableBuilders" />
                <xs:attribute name="key" use="optional" type="xs:string" />
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XMLMapping">
        <xs:sequence>
            <xs:element name="definition" minOccurs="1" maxOccurs="1" type="XMLMappingDefinition" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XMLMappingDefinition" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" processContents="skip" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder" />
            <xs:enumeration value="CastorXMLBuilder" />
            <xs:enumeration value="BeanShellBuilder" />
            <xs:enumeration value="ClassBuilder" />
            <xs:enumeration value="CachingClassBuilder" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor" />
            <xs:enumeration value="com.ail.core.command.ClassAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsAccessor" />
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor" />
            <xs:enumeration value="com.ail.core.command.EJBAccessor" />
            <xs:enumeration value="com.ail.core.command.JaninoAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaScriptAccessor" />
            <xs:enumeration value="com.ail.core.command.JavaAccessor" />
            <xs:enumeration value="com.ail.core.command.JMSAccessor" />
            <xs:enumeration value="com.ail.core.command.QuickRulesAccessor" />
            <xs:enumeration value="com.ail.core.command.VelocityAccessor" />
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor" />
            <xs:enumeration value="com.ail.core.command.XSLTAccessor" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== sangnguyensoftware/openunderwriter/demo-product-loader-hook.war/src/Product/AIL/Demo/IrishBrokerPI/Registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>IBA/PIBA Professional Indemnity</name>
    <timeout>-1</timeout>
    <who>Applied Industrial Logic</who>
    <version>1.0</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>AIL.Base.Registry</parentNamespace>

    <types>

        <service name="CalculatePolicyTaxRule" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/Rules/CalculatePolicyTaxRule.java</parameter>
        </service>

        <service name="AssessPolicyRiskRule" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor">
            <!--uncomment the following parameter to get a full dump of the rules (drl) and rule facts written to -->
            <!--the console during risk assessment                                                                -->
            <!--parameter name="LoggingIndicatorAsString">FULL</parameter-->
            <parameter name="Url">~/Rules/PolicyRating.xls</parameter>
        </service>

        <command name="AssessSectionRisk/Section" key="com.ail.insurance.quotation.AssessSectionRiskCommandImpl">
            <!-- There are no risk assessment rules at the section level for this product, all risk assessment -->
            <!-- is done at the policy level. The NullService has the effect of saying 'do nothing'.           -->
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>

        <type name="Policy" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Policy">
            <parameter name="extends">super.Policy</parameter>
            <parameter name="Url">~/Model/Policy.xml</parameter>
        </type>

        <type name="QuotationPageFlow" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.PageFlow">
            <parameter name="extends">super.QuotationPageFlow</parameter>
            <parameter name="Url">~/PageFlows/QuotationPageFlow.xml</parameter>
        </type>

        <type name="QuotationDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
            <parameter name="Url">~/Documents/QuotationDocument.xml</parameter>
        </type>

        <service name="ConditionsSetupService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/ConditionsSetupService.java</parameter>
        </service>

        <command name="ConditionsSetup" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">ConditionsSetupService</parameter>
        </command>

        <service name="ApplyAgentPremiumService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/ApplyAgentPremiumService.java</parameter>
        </service>

        <command name="ApplyAgentPremium" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">ApplyAgentPremiumService</parameter>
        </command>

        <service name="PlaceOrderService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/PlaceOrderService.java</parameter>
        </service>

        <command name="PlaceOrder" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">PlaceOrderService</parameter>
        </command>
        
        <service name="QuoteSetupService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/QuoteSetupService.java</parameter>
        </service>

        <command name="QuoteSetup" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">QuoteSetupService</parameter>
        </command>
        
        <service name="ValidateCompanyDetailsService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/ValidateCompanyDetailsService.java</parameter>
        </service>

        <command name="ValidateCompanyDetails" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">ValidateCompanyDetailsService</parameter>
        </command>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/integration-test.jar/com/ail/core/document/TestGenerateDocumentDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
    xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>TestProduct default config</name>
    <timeout>600000</timeout>
    <who>factory</who>
    <version>$Revision: 1.7 $</version>

    <group name="ListOfThings">
        <parameter name="Thing One">2000</parameter>
        <parameter name="Thing Two">House</parameter>
        <parameter name="Thing Three">A long windy road</parameter>
        <parameter name="Thing Three and a half">Toad in the hole</parameter>
    </group>

    <group name="Products">
    </group>

    <types>

        <!--====================================-->
        <!--   Define the component's services  -->
        <!--====================================-->

        <service name="GenDocService" builder="ClassBuilder"
            key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.document.GenerateDocumentService</parameter>
        </service>

        <!--====================================-->
        <!--  Bind the commands to services     -->
        <!--====================================-->

        <command name="GenerateDoc" builder="ClassBuilder"
            key="com.ail.core.document.GenerateDocumentCommandImpl">
            <parameter name="Service">GenDocService</parameter>
        </command>

        <command name='com.ail.core.product.RegisterProductService.RegisterProductCommand' key='com.ail.core.product.RegisterProductCommandImpl'>
            <parameter name='Service'>com.ail.core.product.catalog.CatalogRegisterProductService</parameter>
        </command>
        <command name='com.ail.core.product.UpdateProductService.UpdateProductCommand' key='com.ail.core.product.UpdateProductCommandImpl'>
            <parameter name='Service'>com.ail.core.product.catalog.CatalogUpdateProductService</parameter>
        </command>
        <command name='com.ail.core.product.ScanForProductDefinitionsService.ScanForProductDefinitionsCommand' key='com.ail.core.product.ScanForProductDefinitionsCommandImpl'>
            <parameter name='Service'>com.ail.core.product.catalog.CatalogScanForProductDefinitionsService</parameter>
        </command>
    </types>

</configuration>

=== sangnguyensoftware/openunderwriter/modules/com/ail/core.jar/com/ail/core/CoreDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file defines the default (factory) configuration for the Core. This configuration is used by the core's resetConfiguration() 
    method. -->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <name>Default Core Configuration</name>
    <timeout>-1</timeout>
    <who>factory</who>
    <version>1.4</version>

	<!-- The number of minutes after which document requests are considered to have expired -->
	<!-- and are eligible for being deleted. -->
    <parameter name="DocumentRequestExpiryMinutes">60</parameter>
    
    <group name="ProductRepository">
        <parameter name="CompanyID">10157</parameter>
        <parameter name="RepositoryID">10197</parameter>
        <parameter name="Root">Product</parameter>
        <parameter name="Protocol">http</parameter>
        <parameter name="Host">localhost</parameter>
        <parameter name="Port">8080</parameter>
        <parameter name="Username">producthandler</parameter>
        <parameter name="Mode">Automatic</parameter>
        <parameter name="UpgradeUsername">upgradehandler</parameter>
    </group>
    
    <group name="VelocityFunctionClasses">
        <parameter name="CoreFunctions">com.ail.core.Functions</parameter>
        <parameter name="InsuranceFunctions">com.ail.insurance.Functions</parameter>
        <parameter name="FinancialFunctions">com.ail.financial.Functions</parameter>
        <parameter name="PageFlowFunctions">com.ail.pageflow.util.Functions</parameter>
        <parameter name="CoreContext">com.ail.core.CoreContext</parameter>
        <parameter name="PageFlowContext">com.ail.pageflow.PageFlowContext</parameter>
        <parameter name="DateTimeUtils">com.ail.core.DateTimeUtils</parameter>
    </group>

    <group name="JEEAccessorContext">
        <!--
        In most deployments these settings are picked up from the server's environment, but in some
        circumstances it can be useful to override them - particularly if your client is accessing 
        remote EJBs.
        
        <parameter name="java.naming.factory.url.pkgs">org.jboss.ejb.client.naming</parameter>
        <parameter name="java.naming.factory.initial">org.jboss.naming.remote.client.InitialContextFactory</parameter>
        <parameter name="java.naming.provider.url">remote://localhost:4447</parameter>
        <parameter name="jboss.naming.client.ejb.context">true</parameter>
        <parameter name="java.naming.security.principal">openquote</parameter>
        <parameter name="java.naming.security.credentials">password</parameter>
        -->
    </group>

    <types>

        <service name="JMSQueueService" key="com.ail.core.command.JMSAccessor">
            <parameter name="Factory">ConnectionFactory</parameter>
            <parameter name="Queue">queue/OpenUnderwriterCommandQueue</parameter>
        </service>
        <service name="JMSOrderedQueueService" key="com.ail.core.command.JMSAccessor">
            <parameter name="Factory">OrderedConnectionFactory</parameter>
            <parameter name="Queue">queue/OpenUnderwriterCommandQueue</parameter>
        </service>

        <!-- Map all of the logger commands to the stdio logger -->
        <command name="InfoLogger" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="DebugLogger" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="WarningLogger" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="ErrorLogger" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="FatalLogger" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>

        <command name='FetchQuotationDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.quotation.FetchQuoteDocumentService</parameter>
        </command>
        <command name='FetchWordingDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchWordingDocumentService</parameter>
        </command>
        <command name='FetchCertificateDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchCertificateDocumentService</parameter>
        </command>
        <command name='FetchEndorsementDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchEndorsementDocumentService</parameter>
        </command>
        <command name='FetchInvoiceDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchInvoiceDocumentService</parameter>
        </command>
        <command name='FetchPolicyDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchPolicyDocumentService</parameter>
        </command>
        <command name='FetchScheduleDocument' key='com.ail.core.document.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.onrisk.FetchScheduleDocumentService</parameter>
        </command>
        
        <!-- ================================================================== -->
        <!-- Payment commands                                                   -->
        <!-- ================================================================== -->
        <command name="BuyWithPayPalCommand" key="com.ail.payment.PaymentRequestCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.PayPalPaymentRequestService</parameter>
        </command>
        <command name="PayPalPaymentExecutionCommand" key="com.ail.payment.PaymentExecutionCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.PayPalPaymentExecutionService</parameter>
        </command>
        <command name="BuyWitheWAYCommand" key="com.ail.payment.PaymentRequestCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.EwayPaymentRequestService</parameter>
        </command>
        <command name="eWAYPaymentExecutionCommand" key="com.ail.payment.PaymentExecutionCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.EwayPaymentExecutionService</parameter>
        </command>
        <command name="eWAYPaymentResponseCommand" key="com.ail.payment.PaymentResponseCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.EwayPaymentResponseService</parameter>
        </command>
        <command name="eWAYPaymentExecutionCommand" key="com.ail.payment.PaymentExecutionCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.EwayPaymentExecutionService</parameter>
        </command>
        <command name="BuyWithiWinPayCommand" key="com.ail.payment.PaymentRequestCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.IWinPayPaymentRequestService</parameter>
        </command>
        <command name="iWinPayPaymentExecutionCommand" key="com.ail.payment.PaymentExecutionCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.IWinPayPaymentExecutionService</parameter>
        </command>
        <command name="BuyWithSagePayCommand" key="com.ail.payment.PaymentRequestCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.SagePayPaymentRequestService</parameter>
        </command>
        <command name="SagePayPaymentExecutionCommand" key="com.ail.payment.PaymentExecutionCommandImpl">
            <parameter name="Service">com.ail.payment.implementation.SagePayPaymentExecutionService</parameter>
        </command>
        
        <!-- ================================================================== -->
        <!-- DocumentContent persistence lifecycle commands                     -->
        <!-- ================================================================== -->
        <command name="DocumentContentOnSaveCommand" key="com.ail.core.persistence.LifeCycleCommandImpl">
            <parameter name="Service">com.ail.core.document.DocumentContentTableOnSaveService</parameter>
        </command>
        <command name="DocumentContentOnUpdateCommand" key="com.ail.core.persistence.LifeCycleCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>
        <command name="DocumentContentOnDeleteCommand" key="com.ail.core.persistence.LifeCycleCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>
        <command name="DocumentContentOnLoadCommand" key="com.ail.core.persistence.LifeCycleCommandImpl">
            <parameter name="Service">com.ail.core.document.DocumentContentTableOnLoadService</parameter>
        </command>
    </types>
</configuration>

=== sangnguyensoftware/openunderwriter/demo-product-loader-hook.war/src/Product/AIL/Demo/LifePlus/Registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration-1.0.xsd">
    <name>Life Plus product registry</name>
    <timeout>-1</timeout>
    <who>Applied Industrial Logic </who>
    <version>1.4</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>AIL.Base.Registry</parentNamespace>

    <types>
        <service name="InitialiseQuotation" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/InitialiseQuotation.java</parameter>
        </service>

        <service name="AssessBankPaymentOptionsService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/AssessBankPaymentOptionsService.java</parameter>
        </service>
        
        <service name="AssessIWinPayPaymentOptionsService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/AssessIWinPayPaymentOptionsService.java</parameter>
        </service>
        
        <!-- TODO: Delete this when iWinPay requests can be made using mobile numbers -->
        <service name="PopulateIWinPayUserService" builder="CachingClassBuilder" key="com.ail.core.command.JaninoAccessor">
            <parameter name="Url">~/JavaServices/PopulateIWinPayUserService.java</parameter>
        </service>
        
        <service name="AssessPolicyRiskRule" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor" >
            <!--uncomment the following parameter to get a full dump of the rules (drl) and rule facts written to -->
            <!--the console during risk assessment                                                                -->
            <!--parameter name="LoggingIndicatorAsString">FULL</parameter-->
            <parameter name="Url">~/Rules/PolicyRating.xls</parameter>
        </service>

        <command name="InitialiseQuotationCommand" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">InitialiseQuotation</parameter>
        </command>

        <command name="AssessSectionRisk/Section" key="com.ail.insurance.quotation.AssessSectionRiskCommandImpl">
            <!-- There are no risk assessment rules at the section level for this product, all risk assessment -->
            <!-- is done at the policy level. The NullService has the effect of saying 'do nothing'.           -->
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>

        <command name="AssessBankPaymentOptions" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">AssessBankPaymentOptionsService</parameter>
        </command>
        
        <command name="AssessIWinPayPaymentOptions" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">AssessIWinPayPaymentOptionsService</parameter>
        </command>
        
        <!-- TODO: Delete this when iWinPay requests can be made using mobile numbers -->
        <command name="PopulateIWinPayUser" key="com.ail.pageflow.ExecutePageActionCommandImpl">
            <parameter name="Service">PopulateIWinPayUserService</parameter>
        </command>


        <type name="Policy" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Policy">
            <parameter name="Url">~/Model/Policy.xml</parameter>
        </type>
        
        <type name="QuotationPageFlow" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.pageflow.PageFlow">
            <parameter name="extends">super.QuotationPageFlow</parameter>
            <parameter name="Url">~/PageFlows/QuotationPageFlow.xml</parameter>
        </type>
        
        <type name="QuotationDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
			<parameter name="extends">super.QuotationDocument</parameter>
            <parameter name="Url">~/Documents/QuotationDocument.xml</parameter>
        </type>

        <type name="CertificateDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
			<parameter name="extends">super.CertificateDocument</parameter>
            <parameter name="Url">~/Documents/CertificateDocument.xml</parameter>
        </type>

        <type name="WordingDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
			<parameter name="extends">super.WordingDocument</parameter>
            <parameter name="Url">~/Documents/WordingDocument.xml</parameter>
        </type>
        
    </types>
</configuration>
